IMAGENET_1K_CLASSES = {'tench, Tinca tinca': 0, 'goldfish, Carassius auratus': 1,
 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias': 2,
 'tiger shark, Galeocerdo cuvieri': 3, 'hammerhead, hammerhead shark': 4,
 'electric ray, crampfish, numbfish, torpedo': 5, 'stingray': 6, 'cock': 7, 'hen': 8, 'ostrich, Struthio camelus': 9,
 'brambling, Fringilla montifringilla': 10, 'goldfinch, Carduelis carduelis': 11,
 'house finch, linnet, Carpodacus mexicanus': 12, 'junco, snowbird': 13,
 'indigo bunting, indigo finch, indigo bird, Passerina cyanea': 14, 'robin, American robin, Turdus migratorius': 15,
 'bulbul': 16, 'jay': 17, 'magpie': 18, 'chickadee': 19, 'water ouzel, dipper': 20, 'kite': 21,
 'bald eagle, American eagle, Haliaeetus leucocephalus': 22, 'vulture': 23,
 'great grey owl, great gray owl, Strix nebulosa': 24, 'European fire salamander, Salamandra salamandra': 25,
 'common newt, Triturus vulgaris': 26, 'eft': 27, 'spotted salamander, Ambystoma maculatum': 28,
 'axolotl, mud puppy, Ambystoma mexicanum': 29, 'bullfrog, Rana catesbeiana': 30, 'tree frog, tree-frog': 31,
 'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui': 32,
 'loggerhead, loggerhead turtle, Caretta caretta': 33,
 'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea': 34, 'mud turtle': 35, 'terrapin': 36,
 'box turtle, box tortoise': 37, 'banded gecko': 38, 'common iguana, iguana, Iguana iguana': 39,
 'American chameleon, anole, Anolis carolinensis': 40, 'whiptail, whiptail lizard': 41, 'agama': 42,
 'frilled lizard, Chlamydosaurus kingi': 43, 'alligator lizard': 44, 'Gila monster, Heloderma suspectum': 45,
 'green lizard, Lacerta viridis': 46, 'African chameleon, Chamaeleo chamaeleon': 47,
 'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis': 48,
 'African crocodile, Nile crocodile, Crocodylus niloticus': 49, 'American alligator, Alligator mississipiensis': 50,
 'triceratops': 51, 'thunder snake, worm snake, Carphophis amoenus': 52,
 'ringneck snake, ring-necked snake, ring snake': 53, 'hognose snake, puff adder, sand viper': 54,
 'green snake, grass snake': 55, 'king snake, kingsnake': 56, 'garter snake, grass snake': 57, 'water snake': 58,
 'vine snake': 59, 'night snake, Hypsiglena torquata': 60, 'boa constrictor, Constrictor constrictor': 61,
 'rock python, rock snake, Python sebae': 62, 'Indian cobra, Naja naja': 63, 'green mamba': 64, 'sea snake': 65,
 'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus': 66,
 'diamondback, diamondback rattlesnake, Crotalus adamanteus': 67,
 'sidewinder, horned rattlesnake, Crotalus cerastes': 68, 'trilobite': 69,
 'harvestman, daddy longlegs, Phalangium opilio': 70, 'scorpion': 71,
 'black and gold garden spider, Argiope aurantia': 72, 'barn spider, Araneus cavaticus': 73,
 'garden spider, Aranea diademata': 74, 'black widow, Latrodectus mactans': 75, 'tarantula': 76,
 'wolf spider, hunting spider': 77, 'tick': 78, 'centipede': 79, 'black grouse': 80, 'ptarmigan': 81,
 'ruffed grouse, partridge, Bonasa umbellus': 82, 'prairie chicken, prairie grouse, prairie fowl': 83, 'peacock': 84,
 'quail': 85, 'partridge': 86, 'African grey, African gray, Psittacus erithacus': 87, 'macaw': 88,
 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita': 89, 'lorikeet': 90, 'coucal': 91, 'bee eater': 92,
 'hornbill': 93, 'hummingbird': 94, 'jacamar': 95, 'toucan': 96, 'drake': 97,
 'red-breasted merganser, Mergus serrator': 98, 'goose': 99, 'black swan, Cygnus atratus': 100, 'tusker': 101,
 'echidna, spiny anteater, anteater': 102,
 'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus': 103,
 'wallaby, brush kangaroo': 104, 'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus': 105,
 'wombat': 106, 'jellyfish': 107, 'sea anemone, anemone': 108, 'brain coral': 109, 'flatworm, platyhelminth': 110,
 'nematode, nematode worm, roundworm': 111, 'conch': 112, 'snail': 113, 'slug': 114, 'sea slug, nudibranch': 115,
 'chiton, coat-of-mail shell, sea cradle, polyplacophore': 116, 'chambered nautilus, pearly nautilus, nautilus': 117,
 'Dungeness crab, Cancer magister': 118, 'rock crab, Cancer irroratus': 119, 'fiddler crab': 120,
 'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica': 121,
 'American lobster, Northern lobster, Maine lobster, Homarus americanus': 122,
 'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish': 123,
 'crayfish, crawfish, crawdad, crawdaddy': 124, 'hermit crab': 125, 'isopod': 126, 'white stork, Ciconia ciconia': 127,
 'black stork, Ciconia nigra': 128, 'spoonbill': 129, 'flamingo': 130, 'little blue heron, Egretta caerulea': 131,
 'American egret, great white heron, Egretta albus': 132, 'bittern': 133, 'crane': 517, 'limpkin, Aramus pictus': 135,
 'European gallinule, Porphyrio porphyrio': 136, 'American coot, marsh hen, mud hen, water hen, Fulica americana': 137,
 'bustard': 138, 'ruddy turnstone, Arenaria interpres': 139, 'red-backed sandpiper, dunlin, Erolia alpina': 140,
 'redshank, Tringa totanus': 141, 'dowitcher': 142, 'oystercatcher, oyster catcher': 143, 'pelican': 144,
 'king penguin, Aptenodytes patagonica': 145, 'albatross, mollymawk': 146,
 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus': 147,
 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca': 148, 'dugong, Dugong dugon': 149, 'sea lion': 150,
 'Chihuahua': 151, 'Japanese spaniel': 152, 'Maltese dog, Maltese terrier, Maltese': 153,
 'Pekinese, Pekingese, Peke': 154, 'Shih-Tzu': 155, 'Blenheim spaniel': 156, 'papillon': 157, 'toy terrier': 158,
 'Rhodesian ridgeback': 159, 'Afghan hound, Afghan': 160, 'basset, basset hound': 161, 'beagle': 162,
 'bloodhound, sleuthhound': 163, 'bluetick': 164, 'black-and-tan coonhound': 165, 'Walker hound, Walker foxhound': 166,
 'English foxhound': 167, 'redbone': 168, 'borzoi, Russian wolfhound': 169, 'Irish wolfhound': 170,
 'Italian greyhound': 171, 'whippet': 172, 'Ibizan hound, Ibizan Podenco': 173, 'Norwegian elkhound, elkhound': 174,
 'otterhound, otter hound': 175, 'Saluki, gazelle hound': 176, 'Scottish deerhound, deerhound': 177, 'Weimaraner': 178,
 'Staffordshire bullterrier, Staffordshire bull terrier': 179,
 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier': 180,
 'Bedlington terrier': 181, 'Border terrier': 182, 'Kerry blue terrier': 183, 'Irish terrier': 184,
 'Norfolk terrier': 185, 'Norwich terrier': 186, 'Yorkshire terrier': 187, 'wire-haired fox terrier': 188,
 'Lakeland terrier': 189, 'Sealyham terrier, Sealyham': 190, 'Airedale, Airedale terrier': 191,
 'cairn, cairn terrier': 192, 'Australian terrier': 193, 'Dandie Dinmont, Dandie Dinmont terrier': 194,
 'Boston bull, Boston terrier': 195, 'miniature schnauzer': 196, 'giant schnauzer': 197, 'standard schnauzer': 198,
 'Scotch terrier, Scottish terrier, Scottie': 199, 'Tibetan terrier, chrysanthemum dog': 200,
 'silky terrier, Sydney silky': 201, 'soft-coated wheaten terrier': 202, 'West Highland white terrier': 203,
 'Lhasa, Lhasa apso': 204, 'flat-coated retriever': 205, 'curly-coated retriever': 206, 'golden retriever': 207,
 'Labrador retriever': 208, 'Chesapeake Bay retriever': 209, 'German short-haired pointer': 210,
 'vizsla, Hungarian pointer': 211, 'English setter': 212, 'Irish setter, red setter': 213, 'Gordon setter': 214,
 'Brittany spaniel': 215, 'clumber, clumber spaniel': 216, 'English springer, English springer spaniel': 217,
 'Welsh springer spaniel': 218, 'cocker spaniel, English cocker spaniel, cocker': 219, 'Sussex spaniel': 220,
 'Irish water spaniel': 221, 'kuvasz': 222, 'schipperke': 223, 'groenendael': 224, 'malinois': 225, 'briard': 226,
 'kelpie': 227, 'komondor': 228, 'Old English sheepdog, bobtail': 229,
 'Shetland sheepdog, Shetland sheep dog, Shetland': 230, 'collie': 231, 'Border collie': 232,
 'Bouvier des Flandres, Bouviers des Flandres': 233, 'Rottweiler': 234,
 'German shepherd, German shepherd dog, German police dog, alsatian': 235, 'Doberman, Doberman pinscher': 236,
 'miniature pinscher': 237, 'Greater Swiss Mountain dog': 238, 'Bernese mountain dog': 239, 'Appenzeller': 240,
 'EntleBucher': 241, 'boxer': 242, 'bull mastiff': 243, 'Tibetan mastiff': 244, 'French bulldog': 245,
 'Great Dane': 246, 'Saint Bernard, St Bernard': 247, 'Eskimo dog, husky': 248,
 'malamute, malemute, Alaskan malamute': 249, 'Siberian husky': 250, 'dalmatian, coach dog, carriage dog': 251,
 'affenpinscher, monkey pinscher, monkey dog': 252, 'basenji': 253, 'pug, pug-dog': 254, 'Leonberg': 255,
 'Newfoundland, Newfoundland dog': 256, 'Great Pyrenees': 257, 'Samoyed, Samoyede': 258, 'Pomeranian': 259,
 'chow, chow chow': 260, 'keeshond': 261, 'Brabancon griffon': 262, 'Pembroke, Pembroke Welsh corgi': 263,
 'Cardigan, Cardigan Welsh corgi': 264, 'toy poodle': 265, 'miniature poodle': 266, 'standard poodle': 267,
 'Mexican hairless': 268, 'timber wolf, grey wolf, gray wolf, Canis lupus': 269,
 'white wolf, Arctic wolf, Canis lupus tundrarum': 270, 'red wolf, maned wolf, Canis rufus, Canis niger': 271,
 'coyote, prairie wolf, brush wolf, Canis latrans': 272, 'dingo, warrigal, warragal, Canis dingo': 273,
 'dhole, Cuon alpinus': 274, 'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus': 275,
 'hyena, hyaena': 276, 'red fox, Vulpes vulpes': 277, 'kit fox, Vulpes macrotis': 278,
 'Arctic fox, white fox, Alopex lagopus': 279, 'grey fox, gray fox, Urocyon cinereoargenteus': 280,
 'tabby, tabby cat': 281, 'tiger cat': 282, 'Persian cat': 283, 'Siamese cat, Siamese': 284, 'Egyptian cat': 285,
 'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor': 286, 'lynx, catamount': 287,
 'leopard, Panthera pardus': 288, 'snow leopard, ounce, Panthera uncia': 289,
 'jaguar, panther, Panthera onca, Felis onca': 290, 'lion, king of beasts, Panthera leo': 291,
 'tiger, Panthera tigris': 292, 'cheetah, chetah, Acinonyx jubatus': 293, 'brown bear, bruin, Ursus arctos': 294,
 'American black bear, black bear, Ursus americanus, Euarctos americanus': 295,
 'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus': 296, 'sloth bear, Melursus ursinus, Ursus ursinus': 297,
 'mongoose': 298, 'meerkat, mierkat': 299, 'tiger beetle': 300,
 'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle': 301, 'ground beetle, carabid beetle': 302,
 'long-horned beetle, longicorn, longicorn beetle': 303, 'leaf beetle, chrysomelid': 304, 'dung beetle': 305,
 'rhinoceros beetle': 306, 'weevil': 307, 'fly': 308, 'bee': 309, 'ant, emmet, pismire': 310,
 'grasshopper, hopper': 311, 'cricket': 312, 'walking stick, walkingstick, stick insect': 313, 'cockroach, roach': 314,
 'mantis, mantid': 315, 'cicada, cicala': 316, 'leafhopper': 317, 'lacewing, lacewing fly': 318,
 "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk": 319,
 'damselfly': 320, 'admiral': 321, 'ringlet, ringlet butterfly': 322,
 'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus': 323, 'cabbage butterfly': 324,
 'sulphur butterfly, sulfur butterfly': 325, 'lycaenid, lycaenid butterfly': 326, 'starfish, sea star': 327,
 'sea urchin': 328, 'sea cucumber, holothurian': 329, 'wood rabbit, cottontail, cottontail rabbit': 330, 'hare': 331,
 'Angora, Angora rabbit': 332, 'hamster': 333, 'porcupine, hedgehog': 334,
 'fox squirrel, eastern fox squirrel, Sciurus niger': 335, 'marmot': 336, 'beaver': 337,
 'guinea pig, Cavia cobaya': 338, 'sorrel': 339, 'zebra': 340, 'hog, pig, grunter, squealer, Sus scrofa': 341,
 'wild boar, boar, Sus scrofa': 342, 'warthog': 343, 'hippopotamus, hippo, river horse, Hippopotamus amphibius': 344,
 'ox': 345, 'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis': 346, 'bison': 347, 'ram, tup': 348,
 'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis': 349,
 'ibex, Capra ibex': 350, 'hartebeest': 351, 'impala, Aepyceros melampus': 352, 'gazelle': 353,
 'Arabian camel, dromedary, Camelus dromedarius': 354, 'llama': 355, 'weasel': 356, 'mink': 357,
 'polecat, fitch, foulmart, foumart, Mustela putorius': 358, 'black-footed ferret, ferret, Mustela nigripes': 359,
 'otter': 360, 'skunk, polecat, wood pussy': 361, 'badger': 362, 'armadillo': 363,
 'three-toed sloth, ai, Bradypus tridactylus': 364, 'orangutan, orang, orangutang, Pongo pygmaeus': 365,
 'gorilla, Gorilla gorilla': 366, 'chimpanzee, chimp, Pan troglodytes': 367, 'gibbon, Hylobates lar': 368,
 'siamang, Hylobates syndactylus, Symphalangus syndactylus': 369, 'guenon, guenon monkey': 370,
 'patas, hussar monkey, Erythrocebus patas': 371, 'baboon': 372, 'macaque': 373, 'langur': 374,
 'colobus, colobus monkey': 375, 'proboscis monkey, Nasalis larvatus': 376, 'marmoset': 377,
 'capuchin, ringtail, Cebus capucinus': 378, 'howler monkey, howler': 379, 'titi, titi monkey': 380,
 'spider monkey, Ateles geoffroyi': 381, 'squirrel monkey, Saimiri sciureus': 382,
 'Madagascar cat, ring-tailed lemur, Lemur catta': 383, 'indri, indris, Indri indri, Indri brevicaudatus': 384,
 'Indian elephant, Elephas maximus': 385, 'African elephant, Loxodonta africana': 386,
 'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens': 387,
 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca': 388, 'barracouta, snoek': 389, 'eel': 390,
 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch': 391,
 'rock beauty, Holocanthus tricolor': 392, 'anemone fish': 393, 'sturgeon': 394,
 'gar, garfish, garpike, billfish, Lepisosteus osseus': 395, 'lionfish': 396,
 'puffer, pufferfish, blowfish, globefish': 397, 'abacus': 398, 'abaya': 399,
 "academic gown, academic robe, judge's robe": 400, 'accordion, piano accordion, squeeze box': 401,
 'acoustic guitar': 402, 'aircraft carrier, carrier, flattop, attack aircraft carrier': 403, 'airliner': 404,
 'airship, dirigible': 405, 'altar': 406, 'ambulance': 407, 'amphibian, amphibious vehicle': 408, 'analog clock': 409,
 'apiary, bee house': 410, 'apron': 411,
 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin': 412,
 'assault rifle, assault gun': 413, 'backpack, back pack, knapsack, packsack, rucksack, haversack': 414,
 'bakery, bakeshop, bakehouse': 415, 'balance beam, beam': 416, 'balloon': 417,
 'ballpoint, ballpoint pen, ballpen, Biro': 418, 'Band Aid': 419, 'banjo': 420,
 'bannister, banister, balustrade, balusters, handrail': 421, 'barbell': 422, 'barber chair': 423, 'barbershop': 424,
 'barn': 425, 'barometer': 426, 'barrel, cask': 427, 'barrow, garden cart, lawn cart, wheelbarrow': 428,
 'baseball': 429, 'basketball': 430, 'bassinet': 431, 'bassoon': 432, 'bathing cap, swimming cap': 433,
 'bath towel': 434, 'bathtub, bathing tub, bath, tub': 435,
 'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon': 436,
 'beacon, lighthouse, beacon light, pharos': 437, 'beaker': 438, 'bearskin, busby, shako': 439, 'beer bottle': 440,
 'beer glass': 441, 'bell cote, bell cot': 442, 'bib': 443, 'bicycle-built-for-two, tandem bicycle, tandem': 444,
 'bikini, two-piece': 445, 'binder, ring-binder': 446, 'binoculars, field glasses, opera glasses': 447,
 'birdhouse': 448, 'boathouse': 449, 'bobsled, bobsleigh, bob': 450, 'bolo tie, bolo, bola tie, bola': 451,
 'bonnet, poke bonnet': 452, 'bookcase': 453, 'bookshop, bookstore, bookstall': 454, 'bottlecap': 455, 'bow': 456,
 'bow tie, bow-tie, bowtie': 457, 'brass, memorial tablet, plaque': 458, 'brassiere, bra, bandeau': 459,
 'breakwater, groin, groyne, mole, bulwark, seawall, jetty': 460, 'breastplate, aegis, egis': 461, 'broom': 462,
 'bucket, pail': 463, 'buckle': 464, 'bulletproof vest': 465, 'bullet train, bullet': 466,
 'butcher shop, meat market': 467, 'cab, hack, taxi, taxicab': 468, 'caldron, cauldron': 469,
 'candle, taper, wax light': 470, 'cannon': 471, 'canoe': 472, 'can opener, tin opener': 473, 'cardigan': 474,
 'car mirror': 475, 'carousel, carrousel, merry-go-round, roundabout, whirligig': 476, "carpenter's kit, tool kit": 477,
 'carton': 478, 'car wheel': 479,
 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM': 480,
 'cassette': 481, 'cassette player': 482, 'castle': 483, 'catamaran': 484, 'CD player': 485, 'cello, violoncello': 486,
 'cellular telephone, cellular phone, cellphone, cell, mobile phone': 487, 'chain': 488, 'chainlink fence': 489,
 'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour': 490, 'chain saw, chainsaw': 491,
 'chest': 492, 'chiffonier, commode': 493, 'chime, bell, gong': 494, 'china cabinet, china closet': 495,
 'Christmas stocking': 496, 'church, church building': 497,
 'cinema, movie theater, movie theatre, movie house, picture palace': 498, 'cleaver, meat cleaver, chopper': 499,
 'cliff dwelling': 500, 'cloak': 501, 'clog, geta, patten, sabot': 502, 'cocktail shaker': 503, 'coffee mug': 504,
 'coffeepot': 505, 'coil, spiral, volute, whorl, helix': 506, 'combination lock': 507, 'computer keyboard, keypad': 508,
 'confectionery, confectionary, candy store': 509, 'container ship, containership, container vessel': 510,
 'convertible': 511, 'corkscrew, bottle screw': 512, 'cornet, horn, trumpet, trump': 513, 'cowboy boot': 514,
 'cowboy hat, ten-gallon hat': 515, 'cradle': 516, 'crash helmet': 518, 'crate': 519, 'crib, cot': 520,
 'Crock Pot': 521, 'croquet ball': 522, 'crutch': 523, 'cuirass': 524, 'dam, dike, dyke': 525, 'desk': 526,
 'desktop computer': 527, 'dial telephone, dial phone': 528, 'diaper, nappy, napkin': 529, 'digital clock': 530,
 'digital watch': 531, 'dining table, board': 532, 'dishrag, dishcloth': 533,
 'dishwasher, dish washer, dishwashing machine': 534, 'disk brake, disc brake': 535,
 'dock, dockage, docking facility': 536, 'dogsled, dog sled, dog sleigh': 537, 'dome': 538, 'doormat, welcome mat': 539,
 'drilling platform, offshore rig': 540, 'drum, membranophone, tympan': 541, 'drumstick': 542, 'dumbbell': 543,
 'Dutch oven': 544, 'electric fan, blower': 545, 'electric guitar': 546, 'electric locomotive': 547,
 'entertainment center': 548, 'envelope': 549, 'espresso maker': 550, 'face powder': 551, 'feather boa, boa': 552,
 'file, file cabinet, filing cabinet': 553, 'fireboat': 554, 'fire engine, fire truck': 555,
 'fire screen, fireguard': 556, 'flagpole, flagstaff': 557, 'flute, transverse flute': 558, 'folding chair': 559,
 'football helmet': 560, 'forklift': 561, 'fountain': 562, 'fountain pen': 563, 'four-poster': 564, 'freight car': 565,
 'French horn, horn': 566, 'frying pan, frypan, skillet': 567, 'fur coat': 568, 'garbage truck, dustcart': 569,
 'gasmask, respirator, gas helmet': 570, 'gas pump, gasoline pump, petrol pump, island dispenser': 571, 'goblet': 572,
 'go-kart': 573, 'golf ball': 574, 'golfcart, golf cart': 575, 'gondola': 576, 'gong, tam-tam': 577, 'gown': 578,
 'grand piano, grand': 579, 'greenhouse, nursery, glasshouse': 580, 'grille, radiator grille': 581,
 'grocery store, grocery, food market, market': 582, 'guillotine': 583, 'hair slide': 584, 'hair spray': 585,
 'half track': 586, 'hammer': 587, 'hamper': 588, 'hand blower, blow dryer, blow drier, hair dryer, hair drier': 589,
 'hand-held computer, hand-held microcomputer': 590, 'handkerchief, hankie, hanky, hankey': 591,
 'hard disc, hard disk, fixed disk': 592, 'harmonica, mouth organ, harp, mouth harp': 593, 'harp': 594,
 'harvester, reaper': 595, 'hatchet': 596, 'holster': 597, 'home theater, home theatre': 598, 'honeycomb': 599,
 'hook, claw': 600, 'hoopskirt, crinoline': 601, 'horizontal bar, high bar': 602, 'horse cart, horse-cart': 603,
 'hourglass': 604, 'iPod': 605, 'iron, smoothing iron': 606, "jack-o'-lantern": 607, 'jean, blue jean, denim': 608,
 'jeep, landrover': 609, 'jersey, T-shirt, tee shirt': 610, 'jigsaw puzzle': 611, 'jinrikisha, ricksha, rickshaw': 612,
 'joystick': 613, 'kimono': 614, 'knee pad': 615, 'knot': 616, 'lab coat, laboratory coat': 617, 'ladle': 618,
 'lampshade, lamp shade': 619, 'laptop, laptop computer': 620, 'lawn mower, mower': 621, 'lens cap, lens cover': 622,
 'letter opener, paper knife, paperknife': 623, 'library': 624, 'lifeboat': 625,
 'lighter, light, igniter, ignitor': 626, 'limousine, limo': 627, 'liner, ocean liner': 628, 'lipstick, lip rouge': 629,
 'Loafer': 630, 'lotion': 631, 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system': 632,
 "loupe, jeweler's loupe": 633, 'lumbermill, sawmill': 634, 'magnetic compass': 635, 'mailbag, postbag': 636,
 'mailbox, letter box': 637, 'maillot': 638, 'maillot, tank suit': 639, 'manhole cover': 640, 'maraca': 641,
 'marimba, xylophone': 642, 'mask': 643, 'matchstick': 644, 'maypole': 645, 'maze, labyrinth': 646,
 'measuring cup': 647, 'medicine chest, medicine cabinet': 648, 'megalith, megalithic structure': 649,
 'microphone, mike': 650, 'microwave, microwave oven': 651, 'military uniform': 652, 'milk can': 653, 'minibus': 654,
 'miniskirt, mini': 655, 'minivan': 656, 'missile': 657, 'mitten': 658, 'mixing bowl': 659,
 'mobile home, manufactured home': 660, 'Model T': 661, 'modem': 662, 'monastery': 663, 'monitor': 664, 'moped': 665,
 'mortar': 666, 'mortarboard': 667, 'mosque': 668, 'mosquito net': 669, 'motor scooter, scooter': 670,
 'mountain bike, all-terrain bike, off-roader': 671, 'mountain tent': 672, 'mouse, computer mouse': 673,
 'mousetrap': 674, 'moving van': 675, 'muzzle': 676, 'nail': 677, 'neck brace': 678, 'necklace': 679, 'nipple': 680,
 'notebook, notebook computer': 681, 'obelisk': 682, 'oboe, hautboy, hautbois': 683, 'ocarina, sweet potato': 684,
 'odometer, hodometer, mileometer, milometer': 685, 'oil filter': 686, 'organ, pipe organ': 687,
 'oscilloscope, scope, cathode-ray oscilloscope, CRO': 688, 'overskirt': 689, 'oxcart': 690, 'oxygen mask': 691,
 'packet': 692, 'paddle, boat paddle': 693, 'paddlewheel, paddle wheel': 694, 'padlock': 695, 'paintbrush': 696,
 "pajama, pyjama, pj's, jammies": 697, 'palace': 698, 'panpipe, pandean pipe, syrinx': 699, 'paper towel': 700,
 'parachute, chute': 701, 'parallel bars, bars': 702, 'park bench': 703, 'parking meter': 704,
 'passenger car, coach, carriage': 705, 'patio, terrace': 706, 'pay-phone, pay-station': 707,
 'pedestal, plinth, footstall': 708, 'pencil box, pencil case': 709, 'pencil sharpener': 710, 'perfume, essence': 711,
 'Petri dish': 712, 'photocopier': 713, 'pick, plectrum, plectron': 714, 'pickelhaube': 715,
 'picket fence, paling': 716, 'pickup, pickup truck': 717, 'pier': 718, 'piggy bank, penny bank': 719,
 'pill bottle': 720, 'pillow': 721, 'ping-pong ball': 722, 'pinwheel': 723, 'pirate, pirate ship': 724,
 'pitcher, ewer': 725, "plane, carpenter's plane, woodworking plane": 726, 'planetarium': 727, 'plastic bag': 728,
 'plate rack': 729, 'plow, plough': 730, "plunger, plumber's helper": 731, 'Polaroid camera, Polaroid Land camera': 732,
 'pole': 733, 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria': 734, 'poncho': 735,
 'pool table, billiard table, snooker table': 736, 'pop bottle, soda bottle': 737, 'pot, flowerpot': 738,
 "potter's wheel": 739, 'power drill': 740, 'prayer rug, prayer mat': 741, 'printer': 742, 'prison, prison house': 743,
 'projectile, missile': 744, 'projector': 745, 'puck, hockey puck': 746,
 'punching bag, punch bag, punching ball, punchball': 747, 'purse': 748, 'quill, quill pen': 749,
 'quilt, comforter, comfort, puff': 750, 'racer, race car, racing car': 751, 'racket, racquet': 752, 'radiator': 753,
 'radio, wireless': 754, 'radio telescope, radio reflector': 755, 'rain barrel': 756,
 'recreational vehicle, RV, R.V.': 757, 'reel': 758, 'reflex camera': 759, 'refrigerator, icebox': 760,
 'remote control, remote': 761, 'restaurant, eating house, eating place, eatery': 762,
 'revolver, six-gun, six-shooter': 763, 'rifle': 764, 'rocking chair, rocker': 765, 'rotisserie': 766,
 'rubber eraser, rubber, pencil eraser': 767, 'rugby ball': 768, 'rule, ruler': 769, 'running shoe': 770, 'safe': 771,
 'safety pin': 772, 'saltshaker, salt shaker': 773, 'sandal': 774, 'sarong': 775, 'sax, saxophone': 776,
 'scabbard': 777, 'scale, weighing machine': 778, 'school bus': 779, 'schooner': 780, 'scoreboard': 781,
 'screen, CRT screen': 782, 'screw': 783, 'screwdriver': 784, 'seat belt, seatbelt': 785, 'sewing machine': 786,
 'shield, buckler': 787, 'shoe shop, shoe-shop, shoe store': 788, 'shoji': 789, 'shopping basket': 790,
 'shopping cart': 791, 'shovel': 792, 'shower cap': 793, 'shower curtain': 794, 'ski': 795, 'ski mask': 796,
 'sleeping bag': 797, 'slide rule, slipstick': 798, 'sliding door': 799, 'slot, one-armed bandit': 800, 'snorkel': 801,
 'snowmobile': 802, 'snowplow, snowplough': 803, 'soap dispenser': 804, 'soccer ball': 805, 'sock': 806,
 'solar dish, solar collector, solar furnace': 807, 'sombrero': 808, 'soup bowl': 809, 'space bar': 810,
 'space heater': 811, 'space shuttle': 812, 'spatula': 813, 'speedboat': 814, "spider web, spider's web": 815,
 'spindle': 816, 'sports car, sport car': 817, 'spotlight, spot': 818, 'stage': 819, 'steam locomotive': 820,
 'steel arch bridge': 821, 'steel drum': 822, 'stethoscope': 823, 'stole': 824, 'stone wall': 825,
 'stopwatch, stop watch': 826, 'stove': 827, 'strainer': 828, 'streetcar, tram, tramcar, trolley, trolley car': 829,
 'stretcher': 830, 'studio couch, day bed': 831, 'stupa, tope': 832, 'submarine, pigboat, sub, U-boat': 833,
 'suit, suit of clothes': 834, 'sundial': 835, 'sunglass': 836, 'sunglasses, dark glasses, shades': 837,
 'sunscreen, sunblock, sun blocker': 838, 'suspension bridge': 839, 'swab, swob, mop': 840, 'sweatshirt': 841,
 'swimming trunks, bathing trunks': 842, 'swing': 843, 'switch, electric switch, electrical switch': 844,
 'syringe': 845, 'table lamp': 846, 'tank, army tank, armored combat vehicle, armoured combat vehicle': 847,
 'tape player': 848, 'teapot': 849, 'teddy, teddy bear': 850, 'television, television system': 851, 'tennis ball': 852,
 'thatch, thatched roof': 853, 'theater curtain, theatre curtain': 854, 'thimble': 855,
 'thresher, thrasher, threshing machine': 856, 'throne': 857, 'tile roof': 858, 'toaster': 859,
 'tobacco shop, tobacconist shop, tobacconist': 860, 'toilet seat': 861, 'torch': 862, 'totem pole': 863,
 'tow truck, tow car, wrecker': 864, 'toyshop': 865, 'tractor': 866,
 'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi': 867, 'tray': 868, 'trench coat': 869,
 'tricycle, trike, velocipede': 870, 'trimaran': 871, 'tripod': 872, 'triumphal arch': 873,
 'trolleybus, trolley coach, trackless trolley': 874, 'trombone': 875, 'tub, vat': 876, 'turnstile': 877,
 'typewriter keyboard': 878, 'umbrella': 879, 'unicycle, monocycle': 880, 'upright, upright piano': 881,
 'vacuum, vacuum cleaner': 882, 'vase': 883, 'vault': 884, 'velvet': 885, 'vending machine': 886, 'vestment': 887,
 'viaduct': 888, 'violin, fiddle': 889, 'volleyball': 890, 'waffle iron': 891, 'wall clock': 892,
 'wallet, billfold, notecase, pocketbook': 893, 'wardrobe, closet, press': 894, 'warplane, military plane': 895,
 'washbasin, handbasin, washbowl, lavabo, wash-hand basin': 896, 'washer, automatic washer, washing machine': 897,
 'water bottle': 898, 'water jug': 899, 'water tower': 900, 'whiskey jug': 901, 'whistle': 902, 'wig': 903,
 'window screen': 904, 'window shade': 905, 'Windsor tie': 906, 'wine bottle': 907, 'wing': 908, 'wok': 909,
 'wooden spoon': 910, 'wool, woolen, woollen': 911, 'worm fence, snake fence, snake-rail fence, Virginia fence': 912,
 'wreck': 913, 'yawl': 914, 'yurt': 915, 'web site, website, internet site, site': 916, 'comic book': 917,
 'crossword puzzle, crossword': 918, 'street sign': 919, 'traffic light, traffic signal, stoplight': 920,
 'book jacket, dust cover, dust jacket, dust wrapper': 921, 'menu': 922, 'plate': 923, 'guacamole': 924,
 'consomme': 925, 'hot pot, hotpot': 926, 'trifle': 927, 'ice cream, icecream': 928,
 'ice lolly, lolly, lollipop, popsicle': 929, 'French loaf': 930, 'bagel, beigel': 931, 'pretzel': 932,
 'cheeseburger': 933, 'hotdog, hot dog, red hot': 934, 'mashed potato': 935, 'head cabbage': 936, 'broccoli': 937,
 'cauliflower': 938, 'zucchini, courgette': 939, 'spaghetti squash': 940, 'acorn squash': 941, 'butternut squash': 942,
 'cucumber, cuke': 943, 'artichoke, globe artichoke': 944, 'bell pepper': 945, 'cardoon': 946, 'mushroom': 947,
 'Granny Smith': 948, 'strawberry': 949, 'orange': 950, 'lemon': 951, 'fig': 952, 'pineapple, ananas': 953,
 'banana': 954, 'jackfruit, jak, jack': 955, 'custard apple': 956, 'pomegranate': 957, 'hay': 958, 'carbonara': 959,
 'chocolate sauce, chocolate syrup': 960, 'dough': 961, 'meat loaf, meatloaf': 962, 'pizza, pizza pie': 963,
 'potpie': 964, 'burrito': 965, 'red wine': 966, 'espresso': 967, 'cup': 968, 'eggnog': 969, 'alp': 970, 'bubble': 971,
 'cliff, drop, drop-off': 972, 'coral reef': 973, 'geyser': 974, 'lakeside, lakeshore': 975,
 'promontory, headland, head, foreland': 976, 'sandbar, sand bar': 977, 'seashore, coast, seacoast, sea-coast': 978,
 'valley, vale': 979, 'volcano': 980, 'ballplayer, baseball player': 981, 'groom, bridegroom': 982, 'scuba diver': 983,
 'rapeseed': 984, 'daisy': 985,
 "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum": 986, 'corn': 987,
 'acorn': 988, 'hip, rose hip, rosehip': 989, 'buckeye, horse chestnut, conker': 990, 'coral fungus': 991,
 'agaric': 992, 'gyromitra': 993, 'stinkhorn, carrion fungus': 994, 'earthstar': 995,
 'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa': 996, 'bolete': 997,
 'ear, spike, capitulum': 998, 'toilet tissue, toilet paper, bathroom tissue': 999}
